"DbUser" = "postgres"
"DbPassword" = "$wip4500$"
"DbName" = "techChallenge"
"DbPort" = "5432"
"DbHost" = "techchallenge.ceqcszpz5onw.us-east-1.rds.amazonaws.com"
"ListenHost" = "localhost"
"ListenPort" = "3000"